### ISSUE TITLE
想要的功能+bug报告

### ISSUE THREAD

**Issue by qinu321** [Aloento/SuperSpineViewer#15]
感谢大佬的超好用工具！
想要的功能如下：
1 可以指定输出fps
（我一般24～30FPS足够）

2输出png时动作一个循环自动停止（或者可以自行指定输出的总帧数）
现在似乎固定600多帧，需要自行找重复循环的地方然后删掉

BUG：
作死打开了json文件（龙骨用的），预览没有显示，那之后打开skel也不会显示预览，重启后解决

**Comment by Aloento** [comment]
1，指定帧率功能会在迁移到DriftFX后增加，目前需要两个渲染系统同步刷新（LWJGL，OpenJFX）不需要高帧率可选择Fast模式

2，动画导出时只会播放一遍，如果发现有重复的情况，则说明动画本身是有重复的动作

3，不可以打开任何龙骨导出的文件。如果卡死，随意打开一个Spine的文件即可解决

**Comment by Aloento** [comment]
不过我有点感兴趣你的第二个问题
不同时长的动画导出的PNG文件数是一定不同的
可以发一个你打开的文件给我看看吗

**Comment by qinu321** [comment]
感谢大佬的细心解答！
png数量确实不同，是我误会了（最先导出的2个动画帧数差不多）
无法输出MOV确实是我把FFmpeg删了的缘故，后来自己发现就修改问题了（不知可不可以用我本来就有的FFmpeg？在压制软件或视频解码软件下都有的）
期待大佬的下次完善更新！

**Comment by Aloento** [comment]
如何检查系统是否安装了FFmpeg
直接在CMD中输入 ffmpeg
看看是否有正常的输出即可
如果有，SSV会默认调用系统的FFmpeg

![image](https://user-images.githubusercontent.com/11802769/105629722-008e1d00-5e45-11eb-86dd-1a5495fee785.png)
