### ISSUE TITLE
去掉了Pre-Alpha但是会出现白边

### ISSUE THREAD

**Issue by s120900225** [Aloento/SuperSpineViewer#19]
一些去掉了Pre-Alpha但是会出现一些白边

**Comment by Aloento** [comment]
给出例子

**Comment by s120900225** [comment]
一些图片开了Pre-Alpha会出现特效挡住人物所以需要去掉
![Uploading 6K]6LZ2HK%N5~M@W67~J($D.png…]()

**Comment by s120900225** [comment]
一些带特效的开了Pre-Alpha会出现特效挡住人物
![6K 6LZ2HK%N5~M@W67~J($D](https://user-images.githubusercontent.com/81162564/111989135-4693f400-8b09-11eb-983e-28a21d7105f9.png)

**Comment by s120900225** [comment]
去掉了Pre-Alpha就会出现白边
![daiji_play_16](https://user-images.githubusercontent.com/81162564/111989595-e3ef2800-8b09-11eb-8df5-c8856c9e0a96.png)
![daiji_play_161](https://user-images.githubusercontent.com/81162564/111989604-e5b8eb80-8b09-11eb-97c2-5f897eca671f.png)

**Comment by s120900225** [comment]
[530202.zip](https://github.com/Aloento/SuperSpineViewer/files/6182119/530202.zip)

**Comment by Aloento** [comment]
SpineUseAlpha是个无效按钮

**Comment by Aloento** [comment]
skeletonRenderer.PremultipliedAlpha = App.globalValues.Alpha;
WPF那个SpineUseAlpha就是我这里的Pre-Alpha

**Comment by Aloento** [comment]
已确认官方就有这个bug，会尝试解决但是不保证能解决

**Comment by Aloento** [comment]
其实那个不是白边，而是透明了，出现在接缝的位置

**Comment by s120900225** [comment]
[dynamic.zip](https://github.com/Aloento/SuperSpineViewer/files/6189808/dynamic.zip)

**Comment by Aloento** [comment]
分析了一下发现这玩意无解...是贴图裁切造成的
