### ISSUE TITLE
导出动画的时候是不完全的

### ISSUE THREAD

**Issue by s120900225** [Aloento/SuperSpineViewer#20]
我在导出一些动画查看的时候发现并不是循环的，而是缺失了一部分，是不完整的循环，在预览则是可以正常循环，导出出来的视频则不是循环而是会缺失了一部分

**Comment by Aloento** [comment]
给出例子

**Comment by Aloento** [comment]
因为捕获开始的太快了，会把播放开始前的动画也给捕获进去一帧
尝试解决
