### ISSUE TITLE
一些图片表现的不完全

### ISSUE THREAD

**Issue by s120900225** [Aloento/SuperSpineViewer#21]
我在spine打开的时候，有一个动画是把眼镜摘了下来，但是在软件上预览的并没有去掉眼镜，而且特效还留了下来
![~_G5$2M@VSL@BCZNPH~( RN](https://user-images.githubusercontent.com/81162564/111984746-af786d80-8b03-11eb-809d-af05afb8f94f.png)
![Uploading 0M{Q6I434Q86[ZB]{6THO6B.png…]()

**Comment by s120900225** [comment]
> 我在spine打开的时候，有一个动画是把眼镜摘了下来，但是在软件上预览的并没有去掉眼镜，而且特效还留了下来

![Uploading 0M{Q6I434Q86[ZB]{6THO6B.png…]()

**Comment by s120900225** [comment]
![0M{Q6I434Q86 ZB {6THO6B](https://user-images.githubusercontent.com/81162564/111985044-0aaa6000-8b04-11eb-92a1-379a4d103938.png)

**Comment by s120900225** [comment]
[新建文件夹.zip](https://github.com/Aloento/SuperSpineViewer/files/6181855/default.zip)

**Comment by Aloento** [comment]
需要出问题的文件

**Comment by Aloento** [comment]
确实有问题，检查中

**Comment by Aloento** [comment]
6f8798c61cc8c3a8e0be43fab5c3bf2f341ba127
已修复
