### ISSUE TITLE
按Export后在设置的路径下并没有看到导出的文件

### ISSUE THREAD

**Issue by Ultrasty** [Aloento/SuperSpineViewer#25]

**Comment by master4life** [comment]
The reason is that he is using chinese characters in sysout. I have recompiled the project with InteliJ, and changed it into English in UTF-8 and now it works fine.

**Comment by Ultrasty** [comment]
那个发布的exe文件不知道为什么导不出文件，我自己编了一遍jar包可以了，支持作者！
