### ISSUE TITLE
疑似贴图读取出问题了。

### ISSUE THREAD

**Issue by xht8723** [Aloento/SuperSpineViewer#26]
![image](https://user-images.githubusercontent.com/15156436/114253784-7c860480-9960-11eb-8862-8f351720b5be.png)
如图，脸部之类的好像没有成功读取，或者是alpha channel的问题？
大佬有什么解决办法吗？

**Comment by xht8723** [comment]
用PS看了一下，发现用AssetStudio导出的png没有alpha channel. 人傻了。

**Comment by Aloento** [comment]
你是没看我的教程吧（，需要自己合成的
