### ISSUE TITLE
2.1.27版本无法读取

### ISSUE THREAD

**Issue by s120900225** [Aloento/SuperSpineViewer#27]
![TB_UR9ZVO4$EY~_T@_~4HNB](https://user-images.githubusercontent.com/81162564/116246336-6c8c6400-a759-11eb-8f98-c4bc546248ed.png)
![image](https://user-images.githubusercontent.com/81162564/116246363-74e49f00-a759-11eb-9652-e34fa49cb551.png)

**Comment by Aloento** [comment]
过旧版本不予兼容
