### ISSUE TITLE
Camera Width 和 Camera Height 无法手动设置

### ISSUE THREAD

**Issue by wzunknown** [Aloento/SuperSpineViewer#28]
拿来试了一下明日方舟二周年红蒂的l2d, 图片比较大, 直接超出范围了, 导出的时候就只能看到 Camera 范围内的图片. 可以用 scale 缩小, 但希望能导出原图.

试了一下发现 Camera 是直接由窗口大小决定的, 所以怎么强行导出全图?

想了一下更合适的需求应该是导出和预览尺寸可以不一样？

不知道需要提供啥信息, 有需要的话之后补充.

**Comment by Aloento** [comment]
迁移到DriftFX后可以解决此问题，目前还不能超采样，或者说其实是可以的但是实现起来很麻烦

**Comment by Aloento** [comment]
曾经最早的版本就是做的超采样，但是会把UI搞得乱七八糟的
