### ISSUE TITLE
导出png序列帧问题

### ISSUE THREAD

**Issue by exe19890522** [Aloento/SuperSpineViewer#32]
请问这个工具的参数调整是否只支持明日方舟这些游戏的？
loadscale xy坐标的调整没有任何改变。
我导入的pine版本是3.5.49的
导出png的时候大量图片是重复的，没有任何动作变化的，请问采集的指标是什么？
一般来说骨骼文件消耗性能大于帧动画，但是采集频率太高了，要么采取固定0.1秒采集图片也行啊。
我还有个问题，既然可以无视版本导入spine动画，那么理论上其实只需要准备一份通用的配置文件就可以了吧？
然后由用户自己决定导出什么格式的配置文件，再配合原本的文件就好了。
我经常遇到二进制的旧版本的spine动画文件的，但是手里只有3.8.75的破解版，还不能切换版本的，否则会报错启动不了
也就没办法用正确的版本打开源文件导出合适的版本配置文件了，要配合cocoscreator用。
我看导出图片的感觉，工具本身就好像是在不断截取区域的图片再导出的吧，否则不应该出现导出图片内容不全的现象。

**Comment by Aloento** [comment]
是在截取渲染出来的图片然后保存，固定0.1秒采集图片那你帧率得有多低
渲染的工作只能由游戏引擎（和GPU）完成，所以暂时没有其他方法
导出没动作变化，那你播放动画的时候有在动么
PNG序列不是拿来直接用的，readme里面说了可以导入pr ae当视频用，PNG序列的目的就是合成视频
如果你想让Spine变成精灵动画（也就是你说的帧动画），那你可以用FFMPEG去降帧率导出序列
输入坐标后按一下回车键
