### ISSUE TITLE
不能导出曲线路径动画

### ISSUE THREAD

**Issue by tl000000** [Aloento/SuperSpineViewer#36]
3.6.53版本的动画和官方的查看器里显示不同，不支持spine的path路径

**Comment by Aloento** [comment]
请给我一个例子

**Comment by tl000000** [comment]
> 请给我一个例子
https://mega.nz/file/AB9VlQTQ#1wdDTAZ6bSM5xKN6wy97IuVBi-UtDh1SJntXO6PXHv4 上传到mega盘了

**Comment by tl000000** [comment]
distortion动画里胸口的那几条蛇的动画

**Comment by Aloento** [comment]
我估计这个问题会在新的重构版本中解决
