### ISSUE TITLE
What is about this Error log

### ISSUE THREAD

**Issue by agno7766** [Aloento/SuperSpineViewer#40]
I tried to open SuperSpineViewer 1.2.6.exe and it couldn't load up. Instead it left these two logs

[error.log](https://github.com/Aloento/SuperSpineViewer/files/10743112/error.log)
[output.log](https://github.com/Aloento/SuperSpineViewer/files/10743113/output.log)

**Comment by Aloento** [comment]
Please ensure that your name of png file is same as the atlas file recorded.

This error log showed that it cannot find your png file.

And make sure that you’re using Java15 which better works with my version that you can find in release.
Or use latest version with any Java19+ and VM arg I provided.

If you have any more questions, feel free to reopen this issue.
