### ISSUE TITLE
[Bug] 加载skel时出现错位

### ISSUE THREAD

**Issue by Szzrain** [Aloento/SuperSpineViewer#42]
如图
![20230413180500](https://user-images.githubusercontent.com/54656633/231894234-e8e95dc3-3e2b-4034-8483-5fd6c37b60f8.png)
我正在尝试使用SuperSpineViewer加载明日方舟中夕的动态立绘皮肤
截图图片左边是我使用 SuperSpineViewer 得到的效果
右上部分pr内的视频是我使用另一个 SpineViewer 导出的视频
右下部分是游戏内的效果
SuperSpineViewer加载出来的效果中夕手上那只龙似乎错位了，与其他的SpineViewer以及游戏中的效果不同
我不是很清楚Spine运作的原理，如果作者需要这个skel我可以提供

**Comment by Szzrain** [comment]
补充一下
系统版本：Windows 11 21H2
Java Runtime: 
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-44)
OpenJDK 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
SuperSpineViewer Version: 1.3.0
Quality: Extreme

**Comment by Aloento** [comment]
确实有这么一个问题，我已经计划修复整个SSV的运行时，它现在非常的混乱，不过我需要一段时间

**Comment by Aloento** [comment]
可以再试试最新版，或许已经解决了，如果还有问题，欢迎随时重新打开
