### ISSUE TITLE
特殊透明贴图导出错误

### ISSUE THREAD

**Issue by Aloento** [Aloento/SuperSpineViewer#5]
![spineboy-pro_127](https://user-images.githubusercontent.com/11802769/104126436-d4f73700-535c-11eb-83a1-aee7865cdf83.png)
目前不知道原因，绿色部分是半透明位置，红色不明，预览时没有问题

**Comment by soarteam** [comment]
@HarryG55

**Comment by soarteam** [comment]
有可能是因为ARGB格式问题导致的

**Comment by NONO5527** [comment]
在您的软件里预览动画时是一切正常，但渲染出png序列或者mov时，动画的部分帧会有一些奇怪的色斑

**Comment by Aloento** [comment]
https://github.com/Aloento/SuperSpineViewer/blob/a6b5a93f74fbf2613f2fc2451b42f319728539cb/src/main/java/com/QYun/SuperSpineViewer/RecordFX.java#L146

尝试解决了这个问题
并没有完美解决

**Comment by Aloento** [comment]
在FFmpeg导出时不再有此问题
